- name: Configurar pfSense via API
  hosts: pfsense
  gather_facts: false
  tasks:
    - name: Configurar interfaz LAN
      uri:
        url: "https://{{ ansible_host }}/api/v1/interface/lan"
        method: PUT
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
        body_format: json
        body:
          enable: true
          descr: "LAN principal"
          ipv4_type: "static"
          ipv4_address: "192.168.20.1"
          ipv4_subnet_bits: 24
        status_code: 200

    - name: Crear regla de firewall para permitir ping
      uri:
        url: "https://{{ ansible_host }}/api/v1/firewall/rule"
        method: POST
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
        body_format: json
        body:
          action: "pass"
          interface: "lan"
          protocol: "icmp"
          description: "Permitir ping en LAN"
        status_code: 200
