- name: Desplegar Honeypot Cowrie en VLAN 30
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  collections:
    - community.vmware

  tasks:
    - name: Crear VM Cowrie
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        port: "{{ vcenter_port }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "honeypot-cowrie"
        guest_id: "ubuntu64Guest"
        state: poweredon
        disk:
          - size_gb: 8
            type: thin
            datastore: "{{ datastore }}"
        hardware:
          memory_mb: 1024
          num_cpus: 1
        cdrom:
          - type: iso
            iso_path: "{{ iso_path }}"
            controller_number: 0
            unit_number: 0
          - type: iso
            iso_path: "[{{ datastore }}] seed-cowrie.iso"  # Seed ISO para cloud-init
            controller_number: 0
            unit_number: 1  
        networks:
          - name: "{{ network_vlan30 }}"
        wait_for_ip_address: false
